services:
  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: dev-wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./theme:/var/www/html/wp-content/themes/theme
      - wordpress_data:/var/www/html
    expose:
      - "9000"
 
  db:
    image: mysql:8.3
    container_name: dev-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: dev-nginx
    ports:
      - "8081:80"
    volumes:
      - ./theme:/var/www/html/wp-content/themes/theme
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress

volumes:
  mysql_data:
  wordpress_data:
